### ISSUE TITLE
Add CustomModelData for access items and item buttons

### ISSUE THREAD

**Issue by SofiaRedmond** [kejonaMC/CrossplatForms#112]
### What feature do you want to see added?

- Custom model data for acces items.
- Add a "Forms" folder and the capacity to make a file for each form insted of one file for all forms.
  
 ![image](https://user-images.githubusercontent.com/86848962/184153390-261f629d-4785-4d7a-8f59-8d303e8cd4fc.png)

- Conditional forms/buttons
If PLAYER have X permission, show "A" button, if not, shows "B"  button instead, and same with forms If PLAYER have X permission show "form1", if not, show "B" form instead. 
This will alow us to make one-time shops or show specific buttons/forms to different ranked players for example.

### Are there any alternatives?

- All of this i tried with "command pannels" plugin, but inventory menus are no practical for console players. (Xbox, PS, Switch..)

**Comment by Konicai** [comment]
This issue will track custom model data, but there are already issues for conditions and individual config files. Thanks for the feature request though :)

**Comment by Konicai** [comment]
Experimental support is available on the dev branch

**Comment by Konicai** [comment]
Closed in #168: `custom-model-data`
