### ISSUE TITLE
Player filler lists aren't displaying head icons

### ISSUE THREAD

**Issue by tobi-polar** [kejonaMC/CrossplatForms#125]
### Describe the bug

The filler list that shows all of the players currently online as an input argument doesn't show player head icons next to names as intended. The form tries to load head icons but then fails and the buttons turn to full width buttons instead.

### To Reproduce

1.Make any form that uses the player filler for an argument (/tpa <playername> for example or /pay <playername>)
2. Attempt to use the form and get to the list of players

### Expected behaviour

Expecting that player heads show up next to their names.

### Screenshots / Videos

![player list](https://user-images.githubusercontent.com/36657224/196109066-026229bd-35d1-4316-9555-185fb38d70d0.PNG)

### Geyser Dump

https://dump.geysermc.org/mHGpHiHz50VC9JIfwc1jvBhxrxq99uP9

### CrossplatForms Version

Version: 1.4.0 Branch:main Build:28 Commit:9b2ad7c

**Comment by Konicai** [comment]
Can you try with the latest dev build (65 or newer)?

**Comment by tobi-polar** [comment]
Confirmed working correctly on dev build 66

**Comment by Konicai** [comment]
Its been merged into main btw. both branches are the same as I write this
