### ISSUE TITLE
allow cforms to find and use aliased/non-registered commands 

### ISSUE THREAD

**Issue by MementoAequitas** [kejonaMC/CrossplatForms#129]
### What feature do you want to see added?

As talked about in the Discord server, 

make changes to 'dispatchCommand' and potentially use 'getPluginCommand' for aliases/non-registered commands (if applicable), or whatever method is best for this feature.

As well, potentially allow for the use of Skript commands made in .sk files.

Discord message link to initial conversation:
https://discord.com/channels/853331530004299807/929122730622726174/1037789791401562124

### Are there any alternatives?

I attempted to use skript to register aliased/custom commands, but does not work as a true registration for 'dispatchCommand'.

**Comment by Konicai** [comment]
Fixed in 9b9a31de1bfa818749d422e2c97e8d25169eefd3
