### ISSUE TITLE
Item doesn't open GUI on click

### ISSUE THREAD

**Issue by starrider23** [kejonaMC/CrossplatForms#142]
### Describe the bug

Upon right clicking the item, nothing happens. No error in chat or console.

### To Reproduce

1. Set an item and give it actions.
2. Right click the item.

### Expected behaviour

The form opens.

### Server Version and Plugins

Proxy: velocity-3.1.2-snapshot :
CrossplatForms, Floodgate, ForcePack, Geyser, LuckPerms, Plan, protocolize, VelocityAutoReconnect, velocityplus, VentureChat

Server : paper-1.19.3-348 :
AdvancedPortals, BanManager, BanManager-WebEnhancer, BuycraftX, CrossplatForms, DecentHolograms, DeluxeHub, DiscordSRV, FastAsyncWorldEdit (WorldEdit), floodgate, LuckPerms, Maintenance, Parkour, PlaceholderAPI, Plan, ProtocolLib, ServersNPC, TAB, Vault, VentureChat, WorldGuard

### Geyser Dump

https://dump.geysermc.org/lLmy48WqTlLWVgTY3T3KaQxhTnR3ha0u

### CrossplatForms Version

36

**Comment by Konicai** [comment]
Can you share the config entry for the access item please

**Comment by starrider346** [comment]
# "action", "bedrock-action", and "java-action" are all allowed. These should be condensed into a single "action" since they are the same.
    action:
      # The form/menu to open
      form: servers
    material: NETHER_STAR
    display-name: "§6Server Selector"
    lore:
      - "Right click me!"
    # First hotbar slot is 0
    slot: 4
    # Which platform the access item should be available to. JAVA for Java Edition only, BEDROCK for Bedrock Edition only, ALL for both.
    platform: ALL
    # Give the access item on server join
    on-join: true
    # Give the access item on player respawn
    on-respawn: true
    # Give the access item on world change
    on-world-change: false
    # Remove on player leave
    persist: false
    # This can be removed since it used the exact same values as the global-permission-defaults.
    permission-defaults:
      POSSESS: TRUE
      EVENT: TRUE
      COMMAND: OP
      PRESERVE: FALSE
      MOVE: FALSE

config-version: 4

**Comment by Konicai** [comment]
It should be `actions` rather than `action`. The default config is correct: https://github.com/kejonaMC/CrossplatForms/blob/main/access-item/src/main/resources/access-items.yml#L25

The comment is misleading though and I'll correct that.
