### ISSUE TITLE
Please add buycommand action to be able to charge users when using any menu item please add option <3

### ISSUE THREAD

**Issue by soypeto** [kejonaMC/CrossplatForms#146]
### What feature do you want to see added?

Please add buycommand action to be able to charge users when using any menu item please add option <3
update for 1.19.3 please

### Are there any alternatives?

Please add buycommand action to be able to charge users when using any menu item please add option <3

**Comment by Konicai** [comment]
Do you just want it to automatically run a command? Or hook into a specific plugin? What do you mean by "buycommand"?

Also the plugin should be fine for 1.19.3

**Comment by Konicai** [comment]
This can be reopened if you clarify
