### ISSUE TITLE
Can the operation of executing instructions distinguish console, op, and player

### ISSUE THREAD

**Issue by HaiXi2912** [kejonaMC/CrossplatForms#153]
### What feature do you want to see added?

Can the operation of executing instructions distinguish console, op, and player？

for instance：

player;
op;
console;

### Are there any alternatives?

Some of my instructions need to be executed by the player himself, because I need to check his quan

**Comment by Konicai** [comment]
This already exists https://github.com/kejonaMC/CrossplatForms/wiki/Shared-Configuration-Members#commands
