### ISSUE TITLE
Customizable Messages

### ISSUE THREAD

**Issue by HornMCPE** [kejonaMC/CrossplatForms#171]
### What feature do you want to see added?

Hi, I liked this plugin, it's Useful for my Minecraft server as it will be cross-platforms. but i really want to customize the Messages, like when I type the command of the plugin I can receive a message but i can customize it in messages.yml or config.yml, pls i really need this feature as my server's primary language is not English, Thanks!

### Are there any alternatives?

I tried going on Jar file, but My 7 days trial on Intellij just finished so i can't open CLASS file.

**Comment by Konicai** [comment]
This will be covered by #12. I understand the necessity, thank you for the feature request.

Also, if you use IntelliJ IDEA Community Edition, there shouldn't be any trial (it is free)

**Comment by HornMCPE** [comment]
thanks for informing me for Intellij IDEA Community Edition! thanks for your active support
