### ISSUE TITLE
Improve should-show option

### ISSUE THREAD

**Issue by 0372JesusMtz0372** [kejonaMC/CrossplatForms#184]
### What feature do you want to see added?

**Description**
When using the should option "show: %placeholder%" you can specify the value that the placeholder should return to display the button and also specify whether the value of the placeholder should be equal or not to display the button

**Example**
should-show: %placeholder%
  equals: "value"
  show: yes/no

#yes - If the value is equal to the specification, show the button
#no - If the value is not equal to the specification, show the button 

### Are there any alternatives?

1. Use the changeoutput placeholder only to change the value of the placeholder to true or false.

**Comment by Konicai** [comment]
Another alternative is using the `string` papi extension.

More advanced conditional logic will be implemented in #63, so I'll close this in favour of that.

**Comment by 0372JesusMtz0372** [comment]
I do not think it is the best, it is better to add the options in the plugin and that it does not depend on other things, do not be lazy and improve your plugin with all due respect, this plugin could become very well known if you will work on it and do it in the best way

**Comment by 0372JesusMtz0372** [comment]
And just don't make the excuse that you don't have time since you just don't want to do what's best for the plugin

**Comment by Jens-Co** [comment]
We do not want to reinvent the wheel, As Konica states "More advanced conditional logic will be implemented in https://github.com/kejonaMC/CrossplatForms/issues/63, so I'll close this in favour of that." there are a lot good decent plugins for conditionals.

**Comment by Konicai** [comment]
> I do not think it is the best, it is better to add the options in the plugin and that it does not depend on other things

Implementing something that has been done multiple times will just take more time and be less powerful. Having to maintain it will mean less time for other features and fixes. There is zero issue with adding usage of another library to this project. 

> do not be lazy and improve your plugin with all due respect, this plugin could become very well known if you will work on it and do it in the best way

Say


I value balance in my life, hobbies

**Comment by Konicai** [comment]
> I do not think it is the best, it is better to add the options in the plugin and that it does not depend on other things

Implementing something that has been done multiple times will just take more time and be less powerful. Having to maintain it will mean less time for other features and fixes. There is zero issue with adding usage of another library to this project. 

> do not be lazy and improve your plugin with all due respect, this plugin could become very well known if you will work on it and do it in the best way

Saying rude stuff like this will just leave a bitter taste in my mouth. I value balance in my life, hobbies, school, and work more than whatever you think of this plugin or what it could be.

> And just don't make the excuse that you don't have time since you just don't want to do what's best for the plugin

If I didn't care about whats best for this plugin then I would be adding more quick bandaid solutions like `should-show` that increase the technical debt of this project.
It doesn't matter how much time I have. Regardless, when I am programming, there's a high likelihood nowadays that I'm working on Geyser. Which is more important for the Bedrock player experience than this plugin ever will be.
