### ISSUE TITLE
Placeholders not working

### ISSUE THREAD

**Issue by ELIASDOERFEL** [kejonaMC/CrossplatForms#187]
### Describe the bug

Im using GeyserMC to play on my Java Server. I want to make a menu just for bedrock players so thats easier for them to run commands fast. But hte command will be run from console even if i dont write this "console; before. The placeholder "%player_name%" is not working for me and now its impossible to run a command which teleports them to their plots because console said "This command can only be run by a player"

### To Reproduce

1, install geysermc, floodgate and crossplatforms
2. setting up commands run by console with placeholders 
3. try on server with bedrock client
4. error in console invalid player or you must be a player if i dont but the "console; in it

### Expected behaviour

I expect the plugin to get the players name and teleport them to their plot or if there is no "console; before the command it should be run by the player itself

### CrossplatForms Version

1.5.0

**Comment by Konicai** [comment]
> if there is no "console; before the command it should be run by the player itself

changing this would break existing setups

please prefix with `player; ` to make the player run the command
