### ISSUE TITLE
Multifile forms | Condition

### ISSUE THREAD

**Issue by foeyiich** [kejonaMC/CrossplatForms#191]
### What feature do you want to see added?

I hope this plugin can provide a feature for creating forms in different files such as "CrossplatForms/forms/example.yml", I want this so that forms can be more organized 

Condition like "requirements" in DeluxeMenus
I thought that maybe if the plugin could provide an if else feature like "if %some placeholder% contains "text"" it could make forms even more customized 

### Are there any alternatives?

-

**Comment by Konicai** [comment]
Both are already existing feature requests
