### ISSUE TITLE
CrossplatForms BungeeCord Issue

### ISSUE THREAD

**Issue by XPaladiumyX** [kejonaMC/CrossplatForms#192]
### Describe the bug

I'm on WaterFalls Proxy BungeeCord and when i put the plugin and dependencies into plugin files all seems working there is no errors after launching but when i join the server there is no /forms command and when i try to execute it, it says "unknow command please try /help" I'm OP and i have every Permissions and when i try via the console to execute the command it says unknow command too 

### To Reproduce

Install Normally the plugin on a proxy and the error will apear.

### Expected behaviour

That everything works correctly.

### Screenshots / Videos

Command via Chat
![Capture d’écran 2024-02-11 205050](https://github.com/kejonaMC/CrossplatForms/assets/126415682/ceb05db1-a933-46a5-8913-b05bb6156873)
Command via Console
![Capture d’écran 2024-02-11 205135](https://github.com/kejonaMC/CrossplatForms/assets/126415682/74bfa72c-8430-4fcd-838e-94fca998a07d)

### Server Version and Plugins

Server Version : 1.20.1 ( ViaRewind is also installed )
![Capture d’écran 2024-02-11 204141](https://github.com/kejonaMC/CrossplatForms/assets/126415682/d5fc16fb-af0a-4de2-adb8-c4f1f99920f9)
Proxy : WaterFalls 1.20

### Geyser Dump

https://dump.geysermc.org/IdyNDi6pRBVTVvsJhbzQoVDbPGJl6Ru5

### CrossplatForms Version

Latest ( 1.5.0 )

**Comment by Konicai** [comment]
As per the wiki, it is `formsb`. This avoids conflicts if you also install it on backend servers.

https://github.com/kejonaMC/CrossplatForms/wiki/Commands-and-Permissions
